# Generated by Django 2.2.7 on 2019-11-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
                ('guid', models.CharField(max_length=500, unique=True)),
                ('publication_date', models.DateTimeField()),
                ('retrieve_date', models.DateTimeField(null=True)),
                ('read', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.Feed')),
            ],
        ),
    ]
